import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/page";
import Image from "next/image";

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="bg-zinc-50 text-zinc-900" cz-shortcut-listen="true">
        
        
        <div className="p-4 flex justify-center">
          <Image src="/logo1.jpg" alt="logo" width={120} height={120} />
        </div>

        <Navbar />
        
        <main className="min-h-[calc(100vh-160px)]">
          <Toaster />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}